## TODO THIS IS NOT FIXED UP - JUST CHANGED TO MONGODB
applicationApiVersion: v1beta1
properties:

  INSTALL_OPS_MANAGER:
    title: Install Ops Manager
    description: Select Yes to install Ops Manager or No when Ops Manager is deployed
    type: boolean
    default: true

  # Kubernetes internal DNS
  CLUSTER_NAME: 
    title: Anthos cluster DNS name
    type: string
    x-google-marketplace: 
      type: NAME 
    default: cluster.local 

  GLOBAL_ADMIN_EMAIL:  
    type: string
    x-google-marketplace: 
      type: NAME 
  GLOBAL_ADMIN_PASSWORD:
      title: Ops Manager admin password
      type: string
      pattern: .+
      x-google-marketplace:
        type: MASKED_FIELD

  # Mongo Section
  ORG_NAME:
    title: Ops Manager Org Name
    type: string
    x-google-marketplace: 
      type: NAME 
  NAME:
    title: MongoDB Cluster Name
    type: string
    x-google-marketplace: 
      type: NAME
  VERSION:
    title: MongoDB Version number
    type: string
    default: 4.4.2   
  MEMBERS:
    title: Number of nodes in ReplicaSet    
    type: integer
    default: 3
    minimum: 1
  MONGODB_NAMESPACE: { type: string, x-google-marketplace: { type: NAMESPACE } }

  # SECURITY_TLS:
  # SECURITY_CA:


  MONGODB_REQUESTS_CPU:
    title: MongoDB CPU [mCPU]
    description: Default mCPU allocated to new MongoDB clusters (1000 equals one Core)
    type: integer
    default: 1000
    minimum: 100
  MONGODB_LIMITS_CPU:
    title: MongoDB CPU [mCPU]
    description: Default mCPU allocated to new MongoDB clusters (1000 equals one Core)
    type: integer
    default: 1000
    minimum: 100
  MONGODB_REQUESTS_MEM:
    title: MongoDB Memory [GiB]
    description: Default gigabytes allocated to new MongoDB clusters
    type: integer
    default: 1
    minimum: 1
  MONGODB_LIMITS_MEM:
    title: MongoDB Memory [GiB]
    description: Default gigabytes allocated to new MongoDB clusters
    type: integer
    default: 2
    minimum: 1
  MONGODB_STORAGE:
    title: Storage Capacity [GiB]
    description: Default gigabytes allocated to new PVCs
    type: integer
    default: 50
    minimum: 2

  DB_ADMIN_USER: 
    type: string
    title: MongoDB Admin User name
    x-google-marketplace: 
      type: NAME 
    default: admin
  DB_ADMIN_PASSWORD:
    title: Operator admin password
    type: string
    pattern: .+
    x-google-marketplace:
      type: MASKED_FIELD

  INSTALLER_IMAGE: { type: string, x-google-marketplace: { type: DEPLOYER_IMAGE } }


required:
  - GLOBAL_ADMIN_EMAIL
  - GLOBAL_ADMIN_PASSWORD
  - ORG_NAME
  - NAME
  - MONGODB_NAMESPACE
  - DB_ADMIN_USER
  - DB_ADMIN_PASSWORD


x-google-marketplace:
  clusterConstraints:
    istio: { type: UNSUPPORTED }
