
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "mongodb.name" . }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHEAAACGCAYAAADq6WVxAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAACCBJREFUeNrsXV9oFEccnsRABYsXKkQbNQlCC2IlJ43FSiFH64M+GVto+pazkPhWT2rfWo22b7X07JvJQy5vTaE1fUoeWnrBkkJNMaJStCLGPylKLbmAVMFi57f9TTtZdm/vdvb2z933wXCX3M3uzHwzv++b2dm9pnNtG1qFEGkBJBYtTOAPaIrkohlNABIBkAiARAAkgkQAJAIgEQCJIBEAiQBIBEAiSARAIgASAZAIEgGQCIBEACSCRAAkAiCxbrB682aQmFSseWmbePGL06Jn7ueanaMFzVwbpHbvFh0fHJWvr9b8XCAxYKx/p98i75lNm0I7J0gMohFTa0X70JBFYJjkgcSAzAqNuuf27RUta9dG14lAhT+9o1HX1v92PCIBKKkc6+SIo7AZhlkBiTE0K4/v3AGJUZmV9qFBI717eOWKWBwZFfe+nACJYZsVU717MD0tFs+MitLsLMJpmGal/dCgWLd3r+9jPFleFn9OTYtbn54Sj27fhiaGqXdt/f1GZoX0jsLl4siIeFJahrEJS++IuI2HhozMShh6BxId9K5NjjxTs3J/4iuLuDD0DiQGaFZI7+5PTFhmJUy9a3gSg7yS8OvAwdiMvIYgcT2HzDXbtjWGxtfb5DyqKwkg0VDvaH5HbtOvWSG9I5f58PJlsbUwBhLDAm172ChHnolZofkdTcwfTE1Z8zvSUIzEhJiV0uxP1sT8wdQ0wmnYZsX0SgLN7+5K8h5evgJNDNusmEzOld7dl5PzuM3v6prEILY92PUO7jREvTPd9lBvepcYEoPY9lCvehdrEknv1u3bZ2RWGkHvYkliEGalkfQuViQGcSWhEfUuFiQGYVYaWe8iJdF0ZQV6FyGJpisrpHd3z4xYF2Chd5Uh0PsTybTQwvQqg60Pj27dtsImCIyIRGr4Gx8eE3M9O8Vvh3O+dj1T+N1+9mux85fz1qgGQiZRJ5M2Ep1/eae4dOAtayNttaBw/MLpvNj121UrPNMoB0IkceW0YNbanzLX84pYHB21DEtVIVqG5o6j74ueufPWbdO1vPcdJHppnXSYKtTeOvVZ1aGWyKRpCt37vnV8LLEXcBNNoh5qabWFQq1f3aSt9qSb289+A90UET89Q9dNWo3xY4JIN8kEWct4DaqbsXgECunmpQNvigtv7LFWZ/yYoC0fn7R0c8snJxtON2P1HBuaH15777CRCWofHLR0k0wQzVlBYkTQTdCNj4750k0yQTu+/87STbpeCRIjApkgWj9VJojuQvKjm7SXVC0e1KNuJuaxYGSCLry+x7cJUosHpJv1tniQuGe7KRNEuunHBKnFg13XrtbN4kFiH9BHuqlMEC0eVGuClG6SCSLdTPLiQdO5tg0ZUQc/0R7Unh23LSP/hvFZjMRamyC1eEAmyI9uRvloL5DoYIJIN/1eQUkaVr275tku+Zqtx8o9lrr5x+S3lgFqSaWMJv+rOzrE38sl8df169DEqHWzHrdLNhSJOkz3AsVpI1fDkqgQ1C0EYT9FCiQ6IKibeYjMsKciINFuYAK8rS6sJ02BRA8TZPI0DqWbtX7mG0gMyQTR0xdpmRCT/QgXD0y2kahNXrUCSKzKuJhtIwGJMYLpNhKQGCMEsY0EJMYEQWwjAYkxM0Em20hAYgxNkN9tJJgnxhC0ElSrtVWMxBBNEMIpABJBIgASAZAIgESQCIBEACQCIBEkAiARAIkASASJAEgEQCIAEkEiABKBaEA/qbAk0wyaIrloevr0KVoB4RQAiQBIBEAiSARAIgASAZAIEgGQCASKFT9H++P651vly02ZUjIdeO3e75PlMsvvD8uX426fy/xNDnkywvnOZFq/nZR58h7npPx03l7+V0mmokw5mfdmmXxp+ZK35aP6Dbvlk3nsa5ILMs1znvlyeZzq7vY5l63I7X5CfjZcTTvbf1O4jw9EyHElK8ECk28Catxe6kj2SmiVoTJ9rpEwz/n2y5SRn/fJvEWX41NdOm35BmTqorwVlrGTE50r40ZkNbAROO5W93LtbCdxWPsyNWi6woIWPE7uhBmZJ+PQ23JaOeyVVQQeUSOWo0eBiSxwmZccRi81/oL8rEvLN8yjs6JyyjxdfC7qAFkuqwmBrdy5FIFZP+3crB2wjys6o1UsJ8KD16hXZRnXQy4TluWO1+kyqhSprbKeWZVPprIh2EEebvKoIaQDILDIZa6EwIo0UTVSng9OjA9QCLP3bAdkubevaPRKww3nzXmQqRqt4NC4S/IYlO8wf2/S9vm8/PyifNst05h8r+pY8NJ9Wzn10Fs07LRFLk+pCgId27lFK1wvh5tJ/t8ka4ZjeHPRCh2tXhroYhzcwlurYaNleMRmufEo/O6XZfAaBWn5nSKfv1vT44JhedSxUtSpKCpUockr2qXFpoWdDg1bCYknfGiiMhiqcejvdJlRP6+FS6dR0Kd9zykULnEHyXMoy7EGe0WblOZoL2ru1NTIjXN5LlAEoY5SQVRwbOdmrtCAZvP1tMA9JSuCxzwZBpnSfK6UR+9Wnx1n/dbDXF5znkUn/aHIokKRRmipglFOxqaJE3WybAAECj4OdYgjqn5s3nxpom4YsrbK099j/J1ClbFa6O7TK9ZzD6fwRpVz0j0iYZw73Fn5foYNS1oLMVmXETWshc8Ztulp7jgLQZBiQGae206560yZqODYzs3i/1+nyTucoMCjsdspsy1W9zqkalzff8aKNdqx93LPLWnzw04OczvcwhHrzUE1deKO0M1/98Vg0SXLdej2mPI4tvM/AgwAcTwSsXEdThAAAAAASUVORK5CYII=
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "mongodb-prod", "product_id": "mongodb-enterprise-gke-byol", "partner_name": "mongodb"}'
spec:
  descriptor:
    type: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
    description: |-
        This is temp placeholder copy. This is MongoDB Enterprise on GKE Anthos for Google Marketplace.
        TODO TODO - Marketing add copy here - TODO TODO

    maintainers:
    - name: Mongodb, Inc.
      url: https://www.mongodb.com/
    links:
    - description: 'Documentation for Mongodb on Kubernetes'
      url: https://docs.mongodb.com/kubernetes-operator/stable
    - description: 'Getting Started'
      url: https://github.com/mongodb/mongodb-gke/blob/master/README.md
    notes: |-

      ### Intro
      The MongoDB Enterprise Kubernetes Operator translates the human knowledge of creating a MongoDB instance into a scalable, repeatable, and standardized method. Kubernetes needs help creating and managing stateful applications like databases. It needs to configure the network, persist storage, and dedicate computing capacity without additional human effort on each container. 

    The Kubernetes Operator manages the typical lifecycle events for a MongoDB cluster such as provisioning storage and computing power, configuring network connections, setting up users, and changing these settings as needed. It accomplishes this using the Kubernetes API and tools.

You provide the Operator with the specifications for your MongoDB cluster. The Operator uses this information to tell Kubernetes how to configure that cluster including provisioning storage, setting up the network connections, and configuring other resources.


      ### Add notes on install and usage here
      TODO TODO TODO TODO
      TODO TODO TODO TODO

  selector:
    matchLabels:
      release: {{ .Release.Name }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  componentKinds:
  - group: apps/v1
    kind: StatefulSet
  - group: v1
    kind: Service
  - group: v1
    kind: Secret
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
---
